language: node_js
node_js:
  - "6"
script:
  - npm run check
addons:
  code_climate:
    repo_token: b9b1d75d35a4a0abd6cefa9934564d22166b2ff346af0730d20dc70c92af5da8
before_script:
  - npm run setup
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
notifications:
  email: false